export const INVOICE_PAYMENT_ACCOUNT_NAME = "Erepair Limited";
export const INVOICE_PAYMENT_ACCOUNT_NUMBER = "38-9026-0196137-00";
export const INVOICE_PAYMENT_DETAILS = `${INVOICE_PAYMENT_ACCOUNT_NAME} Ac:${INVOICE_PAYMENT_ACCOUNT_NUMBER}`;
